11 implement gene search functionality and gene information page
bihealth/reev pull request #14
Opened 2023-08-22 09:50 UTC by gromdimon

2023-08-23 06:46 UTC, holtgrewe requested changes

2023-08-23 06:46 UTC, holtgrewe commented on backend/app/main.py
> +    print(f"backend_url = {backend_url}", file=sys.stderr)
remove

2023-08-23 06:46 UTC, holtgrewe commented on backend/app/main.py
> +
remove?

2023-08-23 06:46 UTC, holtgrewe commented on frontend/package.json
> +    "axios": "^1.4.0",
we don't want this

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/api/annonars.ts
> +  import.meta.env.MODE == 'development' ? '//localhost:8080/proxy/annonars' : '/proxy/annonars'
Maybe we should an `export const API_BASE_PREFIX` in a more central module (`api/common.ts`?) and import this from there. then use `const API_BASE_URL = \`${API_BASE_PREFIX}/\`` here?

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/components/HeaderDetailPage.vue
> +        <img src="@/assets/reev-logo.png" id="logo" alt="logo" width="100" />
Can't we just use the SVG here?

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/stores/geneInfo.ts
> + *
Remove such trailing comment lines.

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/views/AboutView.vue
> +import Header from '@/components/HeaderDefault.vue'
Should this be `import HeaderDefault`?

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/views/ContactView.vue
> +          <v-btn href="https://github.com/bihealth" target="_blank">
Should be `https://github.com/bihealth/reev/discussions`

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/views/ContactView.vue
> +          <v-btn href="mailto:random.mail@adress.com" target="_blank">
should be cubi-helpdesk@bih-charite.de and we don't need target blank here.

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/views/HomeView.vue
> +// const geneInfoStore = useGeneInfoStore()
Remove such commented out lines.

2023-08-23 06:46 UTC, holtgrewe commented on frontend/tsconfig.app.json
> +    // "composite": true,
remove line?

2023-08-23 06:46 UTC, holtgrewe commented on info?hgnc-id=HGNC:1100
Should this be removed?

2023-08-23 06:46 UTC, holtgrewe commented on package-lock.json
I don't think that we want to have this at the top level. I'ts probably an artifact from running `npm install` in the wrong place.

2023-08-23 06:46 UTC, holtgrewe commented on frontend/src/views/GeneDetailView.vue
> +})
Remove this and the corresponding linkout as well as the stop words ;-)

2023-08-23 10:28 UTC, holtgrewe reviewed
Generally, looks good to me, except for small adjustments.

Next step is to add tests?

2023-08-23 10:28 UTC, holtgrewe commented on frontend/src/api/common.ts
> +
rather use `export const`?

2023-08-23 10:28 UTC, holtgrewe commented on frontend/src/views/HomeView.vue
> +const searchRegexp: [RegExp, RouteLoctionBuilder][] = [
Should probably be called `SEARCH_REGEXPS`.

2023-08-23 10:28 UTC, holtgrewe commented on frontend/tsconfig.app.json
> +    "src/api/utils.ts"
Is this needed?

2023-08-23 10:28 UTC, holtgrewe commented on frontend/src/views/GeneDetailView.vue
> +const sections = [
Name `SECTIONS`?

2023-08-29 07:44 UTC, gromdimon commented
### Some notes:
- We ommit tests in docker builds : see .dockerignore
- `AnnonarsClient` does not properly handles exceptions
- SearchBar selection for genomeRelease is not tested
- HomeView `performSearch` is not tested
- GeneDetailView navigation bar redirections with `#` in url is not tested

2023-08-30 11:22 UTC, merged